version: '3.8'

services:
  civetweb:
    build: .
    container_name: civetweb
    ports:
      - "9001:9001"  # Optional: expose for local testing

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - civetweb

volumes:
  caddy_data:
  caddy_config:
